version: "2"

services: 
  ## Define Consul basics
  consul:
    image: consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    networks:
      - sky-net
      
  ## Define simple-server
  simple-server:
    build:
      context: . 
      dockerfile: server/dockerfile
    image: simple-server:1.0.0
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      - consul
    networks:
      - sky-net

  ## Define simple-client
  simple-client:
    build:
      context: .
      dockerfile: client/dockerfile
    image: simple-client:1.0.0
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    depends_on: ## starts after dependants have been started.
      - consul
      - simple-server
    networks:
      - sky-net


networks:
  sky-net:
    driver: bridge