FROM golang:1.10.1-alpine

ENV SOURCES /go/src/github.com/todai88/udemy-cloud-native-go/advanced/

RUN apk update && apk upgrade && apk add --no-cache bash git openssh
RUN go get github.com/gin-gonic/gin

COPY . ${SOURCES}

RUN cd ${SOURCES} && CGO_ENABLED=0 go build

WORKDIR ${SOURCES}
CMD ${SOURCES}advanced

EXPOSE 8080