version: "2"

services:
  ## kafka dependencies
  zookeeper:
    image: dockerkafka/zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
      - "5000:5000"
    networks:
      - sky-net
  
  kafka:
    image: dockerkafka/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper
    networks:
      - sky-net

  ## own containers
  kafka-producer:
    build:
      context: .
      dockerfile: producer/dockerfile
    image: kafka-producer:1.0.0
    environment:
      - BROKER_ADDR=kafka:9092
    depends_on:
      - zookeeper
      - kafka
    links:
      - kafka
    networks:
      - sky-net
    
  kafka-subscriber:
    build:
      context: .
      dockerfile: subscriber/dockerfile
    image: kafka-subscriber:1.0.0
    environment:
      - BROKER_ADDR=kafka:9092
    depends_on:
      - zookeeper
      - kafka
    links:
      - kafka
    networks:
      - sky-net
  
networks:
  sky-net:
    driver: bridge
